# Aula 3: Perceptron

<img src="../../assets/processo.png" width=400>

<img src="../../assets/perceptron.png" width=400>

In [144]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

a) Carregar a matriz de treinamento

Sendo ela dada por: x1 x2 x3 d (d = saída desejada)

In [145]:
# read treinamento.txt
df = pd.read_csv('treinamento.txt', sep="\t", header=None, names=["x1", "x2", "x3", "d"])
df.columns = ["x1", "x2", "x3", "d"]
df.head()

x1      x2      x3    d
0  1.4715  0.8996  1.1509 -1.0
1  4.6315  0.3409  2.4209 -1.0
2  2.9055  3.1858  3.1770  1.0
3  3.2563  4.3231  3.8009  1.0
4  0.2798  4.0843  2.2521  1.0

b) Implementar T e d a partir de M 

In [146]:
T = df[['x1', 'x2', 'x3']]
T['x0'] = -1
T = T[['x0', 'x1', 'x2', 'x3']]

d = df[['d']]

T.head(), d.head()


(   x0      x1      x2      x3
 0  -1  1.4715  0.8996  1.1509
 1  -1  4.6315  0.3409  2.4209
 2  -1  2.9055  3.1858  3.1770
 3  -1  3.2563  4.3231  3.8009
 4  -1  0.2798  4.0843  2.2521,
      d
 0 -1.0
 1 -1.0
 2  1.0
 3  1.0
 4  1.0)

c) inicializar variáveis

In [147]:
lr = 0.01 
count_epochs = 0
w = np.array([[0], [0], [0], [0]]).astype(float) # theta w1 w2 w3

# fill w with random values (0 to 1)
for i in range(0, 4):
    w[i] = np.random.uniform(0, 1)

w

array([[0.70292861],
       [0.69706798],
       [0.1073461 ],
       [0.70752513]])

d) obter o potencial de ativação

In [148]:
k = 1
x = np.array([T.loc[k].values]).astype(float)

u = np.dot(w.T, x.T)[0][0] # os zeros é pra tirar dos arrays

x, u

(array([[-1.    ,  4.6315,  0.3409,  2.4209]]), 4.274983621622934)

e) treinamento do perceptron 

Regra de Hebb

In [149]:
erro = True
epoca = 0

while erro == True and epoca < 10:
    print('epoca: ', epoca)
    erro = False
    epoca += 1
    for k in range(len(T)):
        x = np.array([T.loc[k].values]).astype(float)
        u = np.dot(w.T, x.T)[0][0]
        y = np.sign(u)
        if y != d.iloc[k][0]:
            w = w + lr * (d.iloc[k][0] - y) * x
            erro = True
            
w 


epoca:  0
epoca:  1
epoca:  2
epoca:  3
epoca:  4
epoca:  5
epoca:  6
epoca:  7
epoca:  8
epoca:  9


array([[ 3.70292861, -6.64551139, -7.18671139, -6.66929139],
       [ 3.69706798, -6.65137202, -7.19257202, -6.67515202],
       [ 3.1073461 , -7.2410939 , -7.7822939 , -7.2648739 ],
       [ 3.70752513, -6.64091487, -7.18211487, -6.66469487]])